// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbkapemepdemaugtvwkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZia2FwZW1lcGRlbWF1Z3R2d2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDI1MTMsImV4cCI6MjA3MjMxODUxM30.ibzJ_geJzdvL7T7heIdREy_hsru4n13gO-Ci4lKOFU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});